description: 组件架构是Zope的核心，但不仅仅属于Zope，准确的说，应该叫做Python组件架构
exclude: [img, __init__.pyc, __init__.py]
order: [getstarted.rst, example.rst, interface.rst, adapter.rst, utility.rst, adapter2.rst,
  zope.rst, case.rst, reference.rst, component-architecture.tex]
title: Zope组件架构
