description: ''
exclude: [stuff, sitemap, site_links, include.rst, index_right_col.rst, left_col.rst,
  navtree.rst, recent.rst, accessibility-info, accessibility.rst, img, index_left_col.rst,
  index_links_col.rst, index_news_col.rst, welcome, ContactInfo, contact-info, front-page,
  newsitems, indexcol.rst.moved, quicklink.rst, demo.rst, agent, cert, essay.rst,
  indexcol.rst, signup.rst, forum.rst, maintain.rst]
order: [index.rst, pyramid, zope, plone, python, projects, blog, about]
theme: index.html
theme_base: http://localhost:6543/themes/czug.org/
theme_default: index.html
title: 易度
