description: 本手册不会涵盖 Python 的所有功能，也不会去解释所用到的所有相关的知识。相反，它介绍了许多 Python 中最引人注目的功能，这会对读者掌握这门语言的风格大有帮助。读过它后，你应该可以阅读和编写
  Python 模块和程序，接下来可以从 Python 库参考手册 中进一步学习Python复杂多变的库和模块。
exclude: [fetch.py]
order: [node0.html, node1.html, node2.html, node3.html, node4.html, node5.html, node6.html,
  node7.html, node8.html, node9.html, node10.html, node11.html, node12.html, node13.html,
  node14.html, node15.html, node16.html, node17.html]
title: 《Python教程》
