description: Deliverance 是一个根据一组规则，将外观套用到内容上的轻量级程序。
exclude: [img, __init__.pyc, __init__.py]
order: [quickstart.rst, philosophy.rst, configuration.rst, pyref.rst, clientside-theming.rst,
  code-map.rst, page-classes.rst, rules.rst, proxy.rst, license.rst]
title: deliverance
