description: 本书可以作为Python编程语言的一本指南或者教程。它主要是为新手而设计，不过对于有经验的程序员来说，它同样有用。
exclude: [fetch.py]
order: [pr01.html, ch01.html, ch02.html, ch03.html, ch04.html, ch05.html, ch06.html,
  ch07.html, ch08.html, ch09.html, ch10.html, ch11.html, ch12.html, ch13.html, ch14.html,
  ch15.html, ch16.html]
title: 《python简明教程》
